<?php

/**
 * Implements hook_library().
 */
function leaflet_label_library() {
  if ($path_locate = libraries_get_path('leaflet_label')) {
    $libraries['leaflet_label'] = array(
      'title' => 'Leaflet Label',
      'version' => 0, // we don't have a version
      'js' => array(
        array(
          'type' => 'file',
          'data' => "$path_locate/dist/leaflet.label.js",
          'group' => JS_LIBRARY,
          'preprocess' => FALSE,
        ),
      ),
      'css' => array(
        "$path_locate/dist/leaflet.label.css" => array(
          'type' => 'file',
          'media' => 'screen',
        ),
      ),
    );
  }

  return $libraries;
}

function leaflet_label_preprocess_leaflet_map(&$vars) {
  drupal_add_library('leaflet_label', 'leaflet_label');
  drupal_add_js(drupal_get_path('module', 'leaflet_label') . '/leaflet_label.drupal.js');
}
